defaults: &defaults
  docker:
    - image: circleci/node:8

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run:
          name: "Install Dependencies"
          command: |
            npm install
            ./node_modules/.bin/lerna bootstrap --hoist
      - save-cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules/
      - run:
          name: "Test"
          command: |
            npm run test:ci
      - run:
          name: "Generate Coverage Report"
          command: |
            npm run test:coverage
      - store_artifacts:
          path: test-results/coverage
          prefix: coverage
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
